# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [2]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [ ]:
# YOUR CODE HERE
# Create an array with integer values
my_array1 = np.array([1, 2, 3, 4, 5])
# Print the shape and type of elements in the array
print("my_array1 shape:", my_array1.shape)
print("my_array1 type of elements:", my_array1.dtype)

# Create an array with mixed data types (integers and strings)
my_array2 = np.array([1, 2, 'apple', 4, 'banana'])

# Print the shape and type of elements in the array
print("my_array2 shape:", my_array2.shape)
print("my_array2 type of elements:", my_array2.dtype)

my_array1 shape: (5,)
my_array1 type of elements: int64
my_array2 shape: (5,)
my_array2 type of elements: <U21


# comment:
my_array1 data is stored as int64 which is raw binary integer values.
my_array2 data is stored as <U21 which is is Unicode encoded text (strings)

---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [ ]:
# YOUR CODE HERE
my_array3 = np.array([1, 2, 3, 4, 5])
print(my_array3.shape)
print(my_array3.size)
print(my_array3.dtype)

(5,)
5
int64


Size represents the number of element in the array.

---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features.

Print the shape of the array.

In [ ]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
# Generate random data using np.random.random() with the given shape
data = np.random.random((num_samples, num_features))

# Print the data and its shape
print("Generated Data:")
print(data)

print("Shape of the Array:")
print(data.shape)

Generated Data:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 ... 2.73875932e-02
  6.70467510e-01 4.17304802e-01]
 [5.58689828e-01 1.40386939e-01 1.98101489e-01 ... 4.21107625e-01
  9.57889530e-01 5.33165285e-01]
 [6.91877114e-01 3.15515631e-01 6.86500928e-01 ... 2.87775339e-01
  1.30028572e-01 1.93669579e-02]
 ...
 [5.94290854e-01 2.31462936e-01 4.26821349e-01 ... 9.11763174e-01
  9.42498874e-01 6.13550027e-01]
 [2.14467781e-01 9.39418871e-01 7.50453547e-01 ... 9.04097157e-02
  1.28975984e-01 1.05262527e-01]
 [1.72727463e-01 1.26430890e-01 7.78300890e-01 ... 8.59998592e-01
  4.58550811e-01 9.30644392e-01]]

Shape of the Array:
(100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [ ]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
# Generate random image data using np.random.random() with the given shape
image_data = np.random.random((num_images, num_rows, num_cols, num_channels))

# Print the data and its shape
print("Generated Image Data:")
print(image_data)

print("\nShape of the Array:")
print(image_data.shape)

Generated Image Data:
[[[[0.25789298 0.93444549 0.61911963]
   [0.98544491 0.03264387 0.72516666]
   [0.56555424 0.49242405 0.25921813]
   ...
   [0.26161079 0.41227893 0.6115441 ]
   [0.54683446 0.38927495 0.10142078]
   [0.7122448  0.08813516 0.86607743]]

  [[0.86344844 0.70845079 0.48642457]
   [0.69914657 0.39498706 0.79749598]
   [0.78641708 0.15552858 0.31781755]
   ...
   [0.96366271 0.59971437 0.00951972]
   [0.41564101 0.02244175 0.31398433]
   [0.48162493 0.57545934 0.2386502 ]]

  [[0.55828658 0.39492013 0.50658219]
   [0.19596701 0.15675161 0.75451701]
   [0.32997323 0.64419569 0.5654556 ]
   ...
   [0.70937379 0.32590872 0.07344017]
   [0.57973705 0.73351702 0.35884603]
   [0.65375147 0.56659141 0.03410642]]

  ...

  [[0.9085518  0.0628612  0.33466736]
   [0.96549291 0.68645273 0.58304565]
   [0.32322443 0.18177244 0.95245839]
   ...
   [0.54658871 0.61293726 0.48044771]
   [0.88533513 0.6138194  0.29664285]
   [0.44180101 0.97973111 0.90294535]]

  [[0.13657883 0.573507

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [ ]:
# YOUR CODE HERE
# Create a (3, 2) numpy array with integer values
my_array4 = np.array([[1, 2], [3, 4], [5, 6]])

# 1. Print the shape of the array
print("Shape of the array:")
print(my_array4.shape)

# 2. Print the sum of all elements
print("\nSum of all elements:")
print(np.sum(my_array4, axis=None))

# 3. Print the sum of all elements by column
print("\nSum of elements by column:")
print(np.sum(my_array4, axis=0))

# 4. Print the sum of all elements by row and change the type of the resulting array elements to float
print("\nSum of elements by row (as float):")
print(np.sum(my_array4, axis=1, dtype=float))

# 5. Print the first row of the array
print("\nFirst row:")
print(my_array4[0])

# 6. Print the second row of the array
print("\nSecond row:")
print(my_array4[1])

# 7. Select the element at position (1, 0)
print("\nElement at position (1, 0):")
print(my_array4[1, 0])

# 8. Modify the element at position (2, 1) by setting its value to 10 and print the array again
my_array4[2, 1] = 10
print("\nArray after modifying element at position (2, 1):")
print(my_array4)

# 9. Loop over elements in the array and print each element
print("\nLooping over elements in the array:")
for row in my_array4:
    for element in row:
        print(element)

Shape of the array:
(3, 2)

Sum of all elements:
21

Sum of elements by column:
[ 9 12]

Sum of elements by row (as float):
[ 3.  7. 11.]

First row:
[1 2]

Second row:
[3 4]

Element at position (1, 0):
3

Array after modifying element at position (2, 1):
[[ 1  2]
 [ 3  4]
 [ 5 10]]

Looping over elements in the array:
1
2
3
4
5
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [ ]:
# YOUR CODE HERE
# Create a (3, 2) numpy array with pixel values between 0 and 1
pixel_values = np.random.random((3, 2))
print("Pixel values (3, 2) array:")
print(pixel_values)
# Create a (27,) numpy array representing years from 1991 to 2017
years = np.arange(1991, 2018)
print("\nYears array (1991 to 2017):")
print(years)
# Create a (3, 5, 10) numpy array filled with zeros
zeros_array = np.zeros((3, 5, 10))
print("\n(3, 5, 10) array of zeros:")
print(zeros_array)
# Create a (3, 5, 10) numpy array filled with ones
ones_array = np.ones((3, 5, 10))
print("\n(3, 5, 10) array of ones:")
print(ones_array)
# Create an array filled with the constant value 5
constant_value_array = np.ones((3, 5, 10)) * 5
print("\nArray with constant value 5:")
print(constant_value_array)
# Create an array with random numbers drawn from a normal distribution
normal_distribution_array = np.random.normal(loc=0, scale=1, size=10)
print("\nArray with random numbers from normal distribution (mean=0, std=1) sample size 10:")
print(normal_distribution_array)

Pixel values (3, 2) array:
[[0.80584041 0.51253926]
 [0.50027804 0.25712724]
 [0.61799302 0.61705604]]

Years array (1991 to 2017):
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]

(3, 5, 10) array of zeros:
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]

(3, 5, 10) array of ones:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [ ]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [ ]:
# YOUR CODE HERE
# 1. Create 3 nested arrays of size (3, 3) from the years array and call it years_3d
years_3d = years.reshape(3, 3, 3)

print("Years 3D array:")
print(years_3d)
print("Shape of years_3d:", years_3d.shape)
# 2. Convert years_3d to a flat 1D array (years_1d)
years_1d = years_3d.flatten()

print("\nYears 1D array:")
print(years_1d)
print("Shape of years_1d:", years_1d.shape)

# 3. Add a new axis (in front) to the years_1d array to create years_2d
years_2d = years_1d[np.newaxis, :]

print("\nYears 2D array (new axis in front):")
print(years_2d)
print("Shape of years_2d:", years_2d.shape)

# 4. Remove the first axis from years_2d to get back to years_1d
years_1d = years_2d.squeeze(axis=0)

print("\nYears 1D array (after removing the first axis):")
print(years_1d)
print("Shape of years_1d:", years_1d.shape)

Years 3D array:
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
Shape of years_3d: (3, 3, 3)

Years 1D array:
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of years_1d: (27,)

Years 2D array (new axis in front):
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
Shape of years_2d: (1, 27)

Years 1D array (after removing the first axis):
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of years_1d: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [ ]:
# YOUR CODE HERE
# Concatenate years_3d along axis 0
result = np.concatenate((years_3d, years_3d), axis=0)
print("\nConcatenate years_3d along axis 0:")
print(result)
print("Shape:", result.shape)
# Concatenate years_2d along axis 1
result = np.concatenate((years_2d, years_2d), axis=1)
print("\nConcatenate years_2d along axis 1:")
print(result)
print("Shape:", result.shape)
# Concatenate years_2d along axis 0
result = np.concatenate((years_2d, years_2d), axis=0)
print("\nConcatenate years_2d along axis 0:")
print(result)
print("Shape:", result.shape)
# Concatenate years_1d along axis 0
result = np.concatenate((years_1d, years_1d), axis=0)
print("\nConcatenate years_1d along axis 0:")
print(result)
print("Shape:", result.shape)
# Stack years_3d along axis 0
result = np.stack((years_3d, years_3d), axis=0)
print("\nStack years_3d along axis 0:")
print(result)
print("Shape:", result.shape)
# Stack years_2d along axis 1
result = np.stack((years_2d, years_2d), axis=1)
print("\nStack years_2d along axis 1:")
print(result)
print("Shape:", result.shape)
# Stack years_2d along axis 0
result = np.stack((years_2d, years_2d), axis=0)
print("\nStack years_2d along axis 0:")
print(result)
print("Shape:", result.shape)
# Stack years_1d along axis 0
result = np.stack((years_1d, years_1d), axis=0)
print("\nStack years_1d along axis 0:")
print(result)
print("Shape:", result.shape)




Concatenate years_3d along axis 0:
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]

 [[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
Shape: (6, 3, 3)

Concatenate years_2d along axis 1:
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 1991
  1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
  2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
Shape: (1, 54)

Concatenate years_2d along axis 0:
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 20

---
#### <span style="color:chocolate">Numpy broadcasting</span>

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [ ]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [ ]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [ ]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [ ]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [3]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01],
       [4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01],
       [8.76389152e-01, 8.94606664e-01, 8.50442114e-02, 3.90547832e-02],
       [1.69830420e-01, 8.78142503e-01, 9.83468338e-02, 4.21107625e-01],
       [9.57889530e-01, 5.33165285e-01, 6.91877114e-01, 3.15515631e-01],
       [6.86500928e-01, 8.34625672e-01, 1.82882773e-02, 7.50144315e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [5]:
# YOUR CODE HERE
# Compute mean and standard deviation along columns (axis=0), with keepdims=True
mean = np.mean(my_array, axis=0, keepdims=True)
std = np.std(my_array, axis=0, keepdims=True)

# Print mean and std for each column
print('\nMean of each column:')
print(mean)
print('\nStandard deviation of each column:')
print(std)

# Standardize the array
standardized_array = (my_array - mean) / std

# Print the standardized array and its shape
print('\nStandardized array:')
print(standardized_array)
print('\nShape of the standardized array:', standardized_array.shape)


Mean of each column:
[[0.5073657  0.68970888 0.19803242 0.44198268]]

Standard deviation of each column:
[[0.28662547 0.25175573 0.20805644 0.23152993]]

Standardized array:
[[-0.31519773  0.12160841 -0.95127097 -0.6031622 ]
 [-1.25812201 -2.37281699 -0.05658183 -0.41645566]
 [-0.38586322 -0.59935931  1.06299085  1.05056318]
 [-1.05682671  0.74837842 -0.8201853   0.98684792]
 [-0.31421109 -0.52042131 -0.27706658 -1.05334626]
 [ 1.02356175  1.10644033  0.55461756  1.08124222]
 [ 1.28747613  0.81387534 -0.54306521 -1.74028424]
 [-1.1776179   0.74847798 -0.47912764 -0.09016135]
 [ 1.57182064 -0.62180746  2.37360926 -0.54622331]
 [ 0.62498014  0.5756246  -0.86392014  1.33097969]]

Shape of the standardized array: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [3]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [7]:
# YOUR CODE HERE
# 1. Crop by using a border of size 1 (remove outer border elements)
cropped_image_1 = my_image[1:-1, 1:-1]  # Slicing to remove outer border (size 1)
print("\nCropped Image (border size 1):")
print(cropped_image_1)
# 2. Crop by removing the first and the last two rows
cropped_image_2 = my_image[2:-2, :]
print("\nCropped Image (first and last two rows removed):")
print(cropped_image_2)
# 2. Crop by removing the first and last two columns
cropped_image_3 = my_image[:, 2:-2]  # Slicing to remove the first two and last two columns
print("\nCropped Image (first and last two columns removed):")
print(cropped_image_3)
# 3. Reverse the column order
reversed_columns_image = my_image[:, ::-1]  # Reverse the order of columns
print("\nImage with reversed columns:")
print(reversed_columns_image)
# 4. Set elements divisible by 2 to 0.5
modified_image = my_image.copy()
modified_image[modified_image % 2 == 0] = 0.5
print("\nImage with elements divisible by 2 set to 0.5:")
print(modified_image)


Cropped Image (border size 1):
[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]

Cropped Image (first and last two rows removed):
[[0.4  0.44 0.48 0.52 0.56]]

Cropped Image (first and last two columns removed):
[[0.08]
 [0.28]
 [0.48]
 [0.68]
 [0.88]]

Image with reversed columns:
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]

Image with elements divisible by 2 set to 0.5:
[[0.5  0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
