## Using Colab

A Colab is a list of *cells*. Each cell is either a text cell (like this one) or a code cell (like the one below). To run code cells, you must be connected to a runtime server. Click *Connect* in the toolbar (top-right). Then, to run the cell below:
* Click the **Play icon** in the left gutter of the cell
* Type **Cmd/Ctrl+Enter** to run the cell in place
* Type **Shift+Enter** to run the cell and move focus to the next cell (adding one if none exists)

Check out more keyboard shortcuts in **Tools->Keyboard shortcuts**.

### Warning: Global Variables!

In Colab, all the variables are global: once created, they are accessible from any code cell. However, you should make sure that your whole Colab executes properly from top to bottom. It's a good idea to use **Runtime -> Restart runtime** and then **Runtime -> Run all** to make sure everything works as intended, especially before you submit.

## Numpy

Numpy is a scientific computing library with lots of tools, but at its core is the idea of an n-dimensional array. We will mostly use numpy to create and manipulate arrays. Note that a 1-D array is called a *vector*, a 2-D array is called a *matrix*, and n-D arrays are sometimes referred to as *tensors* (thus, *TensorFlow*, but more on that later).

See the [Numpy Quickstart Guide](https://numpy.org/doc/stable/user/quickstart.html) for more info.

All ndarrays are homogeneous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way. How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array. In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

Ref:
https://numpy.org/doc/stable/reference/arrays.html

In [1]:
# import libs
import numpy as np

## N-Dimensional array

[What is a 1D, 2D, 3D, N-D array?](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [2]:
# Create arrays of N-dims
a = np.arange(6)
b = np.arange(6).reshape(1, 6)
c = np.arange(18).reshape(3, 1, 6)
d = np.arange(24).reshape(4, 1, 6)

In [3]:
print("A array: ")
print(a)
print("----------------")
print("B array: ")
print(b)
print("----------------")
print("C array: ")
print(c)
print("----------------")
print("D array: ")
print(d)

A array: 
[0 1 2 3 4 5]
----------------
B array: 
[[0 1 2 3 4 5]]
----------------
C array: 
[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]]
----------------
D array: 
[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]]


#### Practice



*   What is the shape of the arrays above? Dimension? Size? (use: shape, ndim, size)
*   What migth data with shape of (6,1) vs. (1,6) vs. (6,)  represent? What would be the difference? <br>(i.e., when thinking of using data to build a model as a data scientist)
*   Can you create a single value and no axes (0 "dimension")? (start from the use of arange as above)

#### Your Answers