# Linear Regression (1 feature)

In [ ]:
# Import our standard libraries.
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns  # for nicer plots
sns.set(style='darkgrid')  # default style
import tensorflow as tf

## Data for Linear Regression

Suppose we have a dataset with 2 datapoints, $x^{(0)}$ and $x^{(1)}$. Each datapoint represents the value of a single feature. Because we'll want our model to have a learned *bias* (or *intercept*), we will use an extra feature which will always be set to 1.

In [ ]:
# Here are our inputs.
X = np.array([[1, 3],
              [1, 2]])
Y = np.array([7, 5])

In [ ]:
# check
print('X:', '\n', X, '\nX shape: ', X.shape, '\n')
print('Y:', '\n', Y, '\nY shape: ', Y.shape)

X: 
 [[1 3]
 [1 2]] 
X shape:  (2, 2) 

Y: 
 [7 5] 
Y shape:  (2,)


In [ ]:
print('X dimensions:', X.ndim)
print('Y dimensions:', Y.ndim)

X dimensions: 2
Y dimensions: 1


## Example slicing
Practice slicing the input array X.

In [ ]:
# Use slicing to get the first X example (as an array)
x_e0 = X[0,:]
# Use slicing to get the second X example (as an array)
x_e1 = X[1,:]

x_e0, x_e1

(array([1, 3]), array([1, 2]))

## Make predictions
Suppose we are using linear regression. Then the functional form for our model is:

\begin{align}
h(x) &= w_0 + w_1x
\end{align}

Since we're using an extra feature corresponding to the intercept/bias, we can write:

\begin{align}
h(x) &= w_0x_0 + w_1x_1 \\
\end{align}

Given parameter values, practice computing model predictions.

In [ ]:
# Let's use a linear regression model: f(x) = w0 + w1*x1
W = np.array([1, 1])
print('W:', W, 'shape:', W.shape, 'dims: ', W.ndim)

# Compute the prediction of the model for the first X example
pred_e0 = np.dot(W, X[0])
print('pred_e0: ', pred_e0)

# Compute the prediction of the model for the second X example
pred_e1 = np.dot(W, X[1])
print('pred_e1: ', pred_e1)

W: [1 1] shape: (2,) dims:  1
pred_e0:  4
pred_e1:  3


#### NumPy: Dot Product Review

Dot product of two arrays. Specifically,

*   If both a and b are 1-D arrays, it is inner product of vectors
*   If both a and b are 2-D arrays, it is matrix multiplication (*See class slides for more info*)

[Refer to NumPy docs here](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).


The dot product between two vectors is a scalar and that only vectors with the same number of elements are compatible for a dot product.

The dot product between a matrix x and a vector y returns a vector where the coefficients are the dot products between y and the rows of x.

**Note**: When one of the two tensors has an ndim greater than 1, dot is no longer symmetric, which is to say that dot(x, y) isn’t the same as dot(y, x).

Ref.: Francois Chollet, [see here](https://learning.oreilly.com/library/view/deep-learning-with/9781617296864/Text/02.htm#heading_id_20)


In [ ]:
# Let's see in more detail

print('W: ', W)
print('X[0]:', X[0])

dot_product = np.dot(W, X[0])
print(dot_product)  # Output: 4

# Explanation:
# (1 * 1) + (1 * 3) = 1 + 3 = 4


W:  [1 1]
X[0]: [1 3]
4


Let's rewrite our model function with matrix multiplication and using the notation $h_W$ to make clear that our model is *parameterized* by $W$ (the vector of parameters):

\begin{align}
h_W(x) = w_0x_0 + w_1x_1 = xW^T
\end{align}

To make this matrix formulation as clear as possible, this is:

\begin{align}
\hat{y} = h_W(x) = xW^T =
\begin{pmatrix}
x_0 & x_1 \\
\end{pmatrix}
\begin{pmatrix}
w_0 \\
w_1 \\
\end{pmatrix}
\end{align}

In addition, if we wanted to apply our model to *all* inputs $X$, we could simply use $XW^T$:

\begin{align}
\hat{Y} = h_W(X) = XW^T =
\begin{pmatrix}
x_{0,0} & x_{0,1} \\
x_{1,0} & x_{1,1} \\
\vdots & \vdots \\
x_{m-1,0} & x_{m-1,1} \\
\end{pmatrix}
\begin{pmatrix}
w_0 \\
w_1 \\
\end{pmatrix}
\end{align}

Remember that [matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication) requires the inner dimensions to line up:

\begin{align}
X_{\{m \times n\}} W^T_{\{n \times 1 \}}  = \hat{Y}_{\{m \times 1 \}}
\end{align}

Ok your turn.

Use numpy functions to compute predictions for both X examples at once. The result should be a vector with 2 entries.

In [ ]:
# Compute predictions for all X examples at once.

print(X, '\n------\n',W)

#X: 2x2
#W.T: 2x1
#Y_hat: 2x1
preds = np.dot(X, W.T)
print('preds:',preds)

[[1 3]
 [1 2]] 
------
 [1 1]
preds: [4 3]


## Loss
Use numpy functions to compute a vector of differences between model predictions and labels (values of Y).

In [ ]:
# Compute differences between predictions and labels.
diff = preds - Y
print(diff)

[-3 -2]


Now compute the MSE loss. The result should be a single (scalar) value. Remember we're using this formula (see assignment 1):

\begin{align}
J(W) = \frac{1}{2m} \sum_{i=0}^{m-1} (h_W(x^{(i)}) - y^{(i)})^2
\end{align}

where we've changed the standard scaling from $\frac{1}{m}$ to $\frac{1}{2m}$, where $m$ is the number of examples (2, in our case).

In [ ]:
# Get the number of examples
m = X.shape[0]
print('shape:', m)

# Compute the average per-example loss
loss = np.sum(diff**2) / m
print('loss:', loss)

shape: 2
loss: 6.5


## Gradient

Refer to assignment 1 or the gradient descent lecture for the derivation, but here's the formula for the partial derivatives (which together form the gradient):

\begin{align}
\frac{\partial}{\partial w_j} J(W) &= (h_W(x) - y)x_j
\end{align}

This formula is assuming we only have a single example. The general formula has an average over examples:

\begin{align}
\frac{\partial}{\partial w_j} J(W) &= \frac{1}{m}\sum_i(h_W(x^{(i)}) - y^{(i)})x^{(i)}_j
\end{align}

You're ready to compute the gradient. The result will be a vector of partial derivatives for $w_0$ and $w_1$ respectively. You can use matrix computations as before.

\begin{align}
\nabla J(W) &= \frac{1}{m}(h_W(X) - Y)X
\end{align}

In [ ]:
# compute the gradient
gradient = np.dot(diff, X) / m
print(gradient)

[-2.5 -6.5]


## Parameter updates
Now that you've computed the gradient, apply parameter updates by subtracting the appropriate partial derivatives (scaled by a learning rate) from the initial parameter values.


In [ ]:
# Update parameter values
learning_rate = 0.1
W = W - learning_rate*gradient
print(W)

[1.25 1.65]


# Linear Regression (multiple features)

Suppose we have a dataset with 2 datapoints, $x^{(0)}$ and $x^{(1)}$, but now we have multiple features.

In [ ]:
# Here are our inputs.
X = np.array([[1, 3, 1, 1],
              [1, 2, 2, 0]])
Y = np.array([2, 1])

Let's write out our model function:

\begin{align}
h_W(x) = w_0x_0 + w_1x_1 + w_2x_2 + w_3x_3 = xW^T
\end{align}

We can get all predictions with this matrix product:

\begin{align}
\hat{Y} = h_W(X) = XW^T =
\begin{pmatrix}
x_{0,0} & x_{0,1} & x_{0,2} & x_{0,3} \\
x_{1,0} & x_{1,1} & x_{1,2} & x_{1,3} \\
\vdots & \vdots & \vdots & \vdots \\
x_{m-1,0} & x_{m-1,1} & x_{m-1,2} & x_{m-1,3} \\
\end{pmatrix}
\begin{pmatrix}
w_0 \\
w_1 \\
w_2 \\
w_3 \\
\end{pmatrix}
\end{align}

Given the (initial) parameter values below, compute the predictions.

In [ ]:
# Initial parameter values.
W = [1, 1, 1, 1]

# Compute predictions.
preds = np.dot(X, W)
print(preds)

[6 5]


Now compute the gradient.

In [ ]:
m, n = X.shape
gradient = np.dot((preds - Y), X) / m
print(gradient)

[ 4. 10.  6.  2.]


And now put everything together in gradient descent. You can run this cell repeatedly.

In [ ]:
# Run gradient descent
learning_rate = 0.1

preds = np.dot(X, W)
loss = ((preds - Y)**2).mean()
gradient = 2 * np.dot((preds - Y), X) / m
W = W - learning_rate * gradient

print('predictions:', preds)
print('loss:', loss)
print('gradient:', gradient)
print('weights:', W)

predictions: [6 5]
loss: 16.0
gradient: [ 8. 20. 12.  4.]
weights: [ 0.2 -1.  -0.2  0.6]


## Now with TensorFlow/Keras

In [ ]:
tf.keras.backend.clear_session()
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(
    units=1,                     # output dim
    input_shape=[4],             # input dim
    use_bias=False,              # we included the bias in X
    kernel_initializer=tf.ones_initializer,  # initialize params to 1
))
optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
model.compile(loss='mse', optimizer=optimizer)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
history = model.fit(
  x = X,
  y = Y,
  epochs=1,
  batch_size=2,
  verbose=0)
loss = history.history['loss'][0]
weights = model.layers[0].get_weights()[0].T
preds = model.predict(X)

print('predictions:', preds.T)
print('loss:', loss)
print('W:', weights)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
predictions: [[-2.4 -2.2]]
loss: 16.0
W: [[ 0.19999999 -1.         -0.20000005  0.6       ]]
